### ISSUE TITLE
Feature Request: A way to exclude pk3/wad file name from monster

### ISSUE THREAD

**Issue by mridlen** [mmaulwurff/target-spy#22]
I'm loading wads from a pk3 and it's a lot of info to see:

MonsterName@Realm667.pk3@Monstername.wad@Decorate

All I want to see is "MonsterName", anything from the first "@" is useless to me

BTW, I'm loving this mod! Thank you for your work on this!

**Comment by mmaulwurff** [comment]
Can you please share a link to the pk3 you are talking about?

**Comment by mridlen** [comment]
https://github.com/mridlen/Oblige_Realm667/blob/master/Realm667.pk3

And example wad that uses these monsters:
https://www.dropbox.com/s/fajjpwh3qyr0ypq/gateway_of_horror.wad?dl=0

**Comment by mmaulwurff** [comment]
To me it looks like an error in Realm667.pk3. Enemies defined twice - in DECORATE and in ZScript. GZDoom even complains about it on loading:
```
Script warning, "Realm667.pk3:sniperzombie.wad:DECORATE" line 1:
Tried to define class 'SniperRifleGuy' more than once. Renaming class to 'SniperRifleGuy@Realm667.pk3@sniperzombie.wad@DECORATE'
```

Or maybe this pk3 isn't supposed to be loaded in this way. Is this mod setup common and/or conventional?

**Comment by mridlen** [comment]
Oh... I suppose I shouldn't use both ZSCRIPT and DECORATE in my wads? I think I'll go back through and redo all the numbers into the ZSCRIPT files and disable the DECORATE files. Thank you, I've been wondering about those warnings.

**Comment by mmaulwurff** [comment]
Just noting that spawn numbers cannot be used in ZScript like they are used in Decorate:
> Game, DoomEdNum, SpawnID and ConversationID cannot be used in ZScript. Use MAPINFO for these instead.
https://zdoom.org/wiki/MAPINFO/Spawn_number_definition

**Comment by mridlen** [comment]
I've went ahead and disabled all the ZSCRIPT instead, since I was using entirely DECORATE. It seems to have resolved my issue. Probably a lazy solution, but this project is a huge undertaking and I just wanted to get it working. Thank you for your help in this matter!

**Comment by mridlen** [comment]
https://www.dropbox.com/s/9eigqcleen6w7fu/Realm667.pk3?dl=0

Updated version (still has warnings, but with secondary things)

**Comment by mmaulwurff** [comment]
![Screenshot_Doom_20200607_100845](https://user-images.githubusercontent.com/742823/83959425-f19f2e00-a8a6-11ea-9248-394c16374440.png)
Problem solved.
