### ISSUE TITLE
add option to display armor as a bar

### ISSUE THREAD

**Issue by mmaulwurff** [mmaulwurff/target-spy#27]
Submitted by Major Cooke via Discord:
> Allow armor to be displayed as a separate bar either above or below the health with the same options as the health. I'm trying to use it as a means of indicating boss phases and it looks a little odd with it displayed as "Armor". Even for non-phase monsters though, that seems a bit odd and a little cluster-some.

To test:
> all you have to do is give a zombie green armor, and that should work

**Comment by MajorCooke** [comment]
Ah, is it possible now? Or still won't be doable? The thing is I'm trying to replicate something akin to Starcraft 2's health and shield system, where there's a blue shield on top of the health bar.
