### ISSUE TITLE
Error when loading with lzdoom

### ISSUE THREAD

**Issue by romadu** [mmaulwurff/target-spy#31]
I'm running lzdoom in linux aarch64 and get an error when trying to load target-spy. 
`Script error, "target-spy-v2.0.1.pk3:zscript/ts_external_actor_info_provider.zs"          line 30:
Unexpected 'abstract'
Expecting '.' or 'class' or identifier or 'native' or 'ui' or 'play' or 'version' or 'color' or 'clearscope' or 'int8' or 'uint8' or 'int16' or 'uint16' or 'int' or 'uint' or 'bool' or 'float' or 'double' or 'vector2' or 'vector3' or 'name' or 'sound' or 'state' or 'let' or '@' or 'readonly' or 'map' or 'array' or 'void' or 'action' or 'deprecated' or 'static' or 'private' or 'protected' or 'latent' or 'final' or 'meta' or 'transient' or 'internal' or 'virtual' or 'override'  or 'vararg' or 'virtualscope'`

Target-spy 1.4.1 also caused an error.
`/lzdoom/src/scripting/backend/codegen.cpp:9401: virtual ExpEmit FxFlopFunctionCall::Emit(VMFunctionBuilder*): Assertion 'ValueType == ArgList[0]->ValueType' failed.`

Is target-spy compatible with lzdoom? I have used 1.4.1 on other installations with lzdoom in linux aarch64 previously without issues

**Comment by mmaulwurff** [comment]
I forgot to add LZDoom version to v2.0.1 release. [Here it is](https://github.com/mmaulwurff/target-spy/releases/download/v2.0.1/target-spy-v2.0.1-lzdoom.pk3).

**Comment by romadu** [comment]
Thank you
