### ISSUE TITLE
add custom text display

### ISSUE THREAD

**Issue by mmaulwurff** [mmaulwurff/target-spy#32]
Submitted by Major Cooke via Discord:

> ... adding custom text to display under the monster's name.
See the word "Archangel" under Malthael?
In Diablo series, they can even display things like "Immune to Poison" in green. This is something that we could take advantage of  with TargetSpy and Service.

![95108f8d89](https://user-images.githubusercontent.com/742823/133914476-542ccd64-b948-46c1-8696-aa317001679e.jpg)

**Comment by MajorCooke** [comment]
Sweet!

**Comment by MajorCooke** [comment]
Other ideas involved with this would include:
- Setting the font size, type, and color to fetch from the service function. That way there's maximum flexibility.
- Overriding flag descriptions(so I could disable certain flags from showing up, for example, or give them alternative names)
